### ISSUE TITLE
Add :target styling

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/ccna#1]
add a colour, i.e. `$accent` to an internal link being clicked on. Useful for both linking from internal sites, as from external sites.

``` scss
*:target {
  color: $accent;
} 
```

Also useful could be to add an animation to the linking.
